---
title: "Problem 2"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(dplyr)
library(rnoaa) 

data("ny_noaa")
ny_noaa= 
  ny_noaa |> 
  mutate(date = ymd(date)) |>
  select(date, prcp, snow, snwd) |>
  filter(
    !is.na(prcp),
    snow != 0
  ) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
box = ny_noaa |> 
  mutate(
    year = year(date)
  ) |> 
  group_by(year) |>
  mutate(year = fct_reorder(as.factor(year), prcp)) |> 
  plot_ly(y = ~prcp, color = ~year, type = "box", colors = "viridis") |>
  layout (yaxis = list(title = "Average PRCP (10^-1)mm"),
          xaxis = list(title = "Year (November)"))

ggplotly(box)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
bar = ny_noaa |> 
  mutate(
    year = year(date),
    month = month(date)
  ) |> 
  filter(month == 11) |>
  group_by(year) |>
  summarize(avg_prcp = mean(prcp, na.rm = TRUE)) |> 
  mutate(year = fct_reorder(as.factor(year), avg_prcp)) |> 
  plot_ly(y = ~avg_prcp, color = ~year, type = "bar", colors = "viridis") |>
  layout (yaxis = list(title = "Average PRCP (10^-1)mm"),
          xaxis = list(title = "Year (November)"))

ggplotly(bar)
```

### Chart C

```{r}
line = ny_noaa |>
  mutate(
    year = year(date),
    month = month(date)  
  ) |>
  group_by(year) |>
  summarize(avg_prcp = mean(prcp, na.rm = TRUE)) |>
  plot_ly(
    x = ~year,
    y = ~avg_prcp,
    type = "scatter",
    mode = "lines",  
    line = list(color = "blue")
  ) |>
  layout(
    yaxis = list(title = "Average Precipitation (prcp)"),
    xaxis = list(title = "Year")
  )

ggplotly(line)
```

